-- Apply after 005. Authenticated editors may delete budgets and budget items.
begin;
create or replace function public.atlas_save_workspace(expected_revision bigint,new_payload jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  saved jsonb; result_payload jsonb; r jsonb; collection text; relation_name text;
  deletion_requested boolean;
  existing_code bigint; generated_budget bigint;
begin
  if auth.uid() is null or coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  -- Lock one global revision before permission checks or any mutations.
  perform 1 from public.atlas_workspaces where user_id='00000000-0000-4000-8000-000000000001'::uuid and revision=expected_revision for update;
  if not found then return null; end if;
  -- Validate collection shape before iterating or deleting records.
  foreach collection in array array['clientes','categorias','itens','orcamentos','itensOrcamento'] loop
    if jsonb_typeof(new_payload->collection) is distinct from 'array' then
      raise exception 'Invalid collection: %',collection using errcode='22023';
    end if;
    for r in select value from jsonb_array_elements(new_payload->collection) loop
      if jsonb_typeof(r) <> 'array' then raise exception 'Invalid row' using errcode='22023'; end if;
      if jsonb_array_length(r) <> (case collection when 'clientes' then 4 when 'categorias' then 2 when 'itens' then 7 else 6 end) then
        raise exception 'Invalid row length' using errcode='22023';
      end if;
    end loop;
  end loop;
  if not public.atlas_is_admin() then
    foreach collection in array array['clientes','categorias','itens'] loop
      relation_name := case collection when 'clientes' then 'cliente' when 'categorias' then 'categoria' when 'itens' then 'produto' else 'orcamento' end;
      execute format('select exists(select 1 from public.%I e where not exists(select 1 from jsonb_array_elements($1) r where (r->>0)::bigint=e.codigo))',relation_name)
        into deletion_requested using new_payload->collection;
      if deletion_requested then raise exception 'Only administrators may delete records' using errcode='42501'; end if;
    end loop;
  end if;
  saved := public.atlas_save_clients_internal(expected_revision,new_payload);
  if saved is null then return null; end if;

  -- Supplied codes must refer to existing rows owned by the caller.
  foreach collection in array array['categorias','itens','orcamentos'] loop
    relation_name := case collection when 'categorias' then 'categoria' when 'itens' then 'produto' else 'orcamento' end;
    if exists(select r0->>0 from jsonb_array_elements(new_payload->collection) r0 where r0->>0 is not null group by r0->>0 having count(*)>1) then
      raise exception 'Duplicate code' using errcode='22023';
    end if;
    for r in select value from jsonb_array_elements(new_payload->collection) loop
      if jsonb_typeof(r->0) not in ('number','null') then raise exception 'Invalid code' using errcode='22023'; end if;
      if r->>0 is not null then
        execute format('select codigo from public.%I where user_id=$1 and codigo=$2',relation_name)
          into existing_code using '00000000-0000-4000-8000-000000000001'::uuid,(r->>0)::bigint;
        if existing_code is null then raise exception 'New codes must be generated by SQL' using errcode='22023'; end if;
      end if;
    end loop;
  end loop;
  if (select count(*) from jsonb_array_elements(new_payload->'orcamentos') r0 where r0->>0 is null)>1 then
    raise exception 'Save one new budget at a time' using errcode='22023';
  end if;

  -- Remove omitted rows in dependency order. Deferred FKs validate final state.
  delete from public.item_orcamento where user_id='00000000-0000-4000-8000-000000000001'::uuid;
  delete from public.orcamento o where o.user_id='00000000-0000-4000-8000-000000000001'::uuid and not exists(select 1 from jsonb_array_elements(new_payload->'orcamentos') r0 where (r0->>0)::bigint=o.codigo);
  delete from public.produto p where p.user_id='00000000-0000-4000-8000-000000000001'::uuid and not exists(select 1 from jsonb_array_elements(new_payload->'itens') r0 where (r0->>0)::bigint=p.codigo);
  delete from public.categoria c where c.user_id='00000000-0000-4000-8000-000000000001'::uuid and not exists(select 1 from jsonb_array_elements(new_payload->'categorias') r0 where (r0->>0)::bigint=c.codigo);

  for r in select value from jsonb_array_elements(new_payload->'categorias') loop
    if r->>0 is null then insert into public.categoria(user_id,descricao) values('00000000-0000-4000-8000-000000000001'::uuid,r->>1);
    else update public.categoria set descricao=r->>1 where user_id='00000000-0000-4000-8000-000000000001'::uuid and codigo=(r->>0)::bigint; end if;
  end loop;
  for r in select value from jsonb_array_elements(new_payload->'itens') loop
    select codigo into existing_code from public.categoria where user_id='00000000-0000-4000-8000-000000000001'::uuid and descricao=r->>1;
    if r->>0 is null then
      insert into public.produto(user_id,categoria_codigo,nome,descricao,valor_venda,status)
        values('00000000-0000-4000-8000-000000000001'::uuid,existing_code,r->>2,r->>3,(r->>4)::numeric,r->>6);
    else
      update public.produto set categoria_codigo=existing_code,nome=r->>2,descricao=r->>3,valor_venda=(r->>4)::numeric,status=r->>6
        where user_id='00000000-0000-4000-8000-000000000001'::uuid and codigo=(r->>0)::bigint;
    end if;
  end loop;
  for r in select value from jsonb_array_elements(new_payload->'orcamentos') loop
    if r->>0 is null then
      insert into public.orcamento(user_id,cliente_codigo,validade,valor_total)
        values('00000000-0000-4000-8000-000000000001'::uuid,(r->>2)::bigint,public.atlas_parse_date(r->>4),0) returning codigo into generated_budget;
    else
      update public.orcamento set cliente_codigo=(r->>2)::bigint,validade=public.atlas_parse_date(r->>4)
        where user_id='00000000-0000-4000-8000-000000000001'::uuid and codigo=(r->>0)::bigint;
    end if;
  end loop;
  for r in select value from jsonb_array_elements(new_payload->'itensOrcamento') loop
    insert into public.item_orcamento(user_id,orcamento_codigo,produto_codigo,produto_nome,quantidade,valor_unitario)
      values('00000000-0000-4000-8000-000000000001'::uuid,coalesce((r->>0)::bigint,generated_budget),(r->>1)::bigint,r->>2,(r->>3)::bigint,(r->>4)::numeric);
  end loop;
  if exists(select 1 from public.orcamento o where o.user_id='00000000-0000-4000-8000-000000000001'::uuid and not exists(select 1 from public.item_orcamento i where (i.user_id,i.orcamento_codigo)=(o.user_id,o.codigo))) then
    raise exception 'Budget requires at least one item' using errcode='23514';
  end if;
  update public.orcamento o set valor_total=(select sum(i.valor_total) from public.item_orcamento i where (i.user_id,i.orcamento_codigo)=(o.user_id,o.codigo)) where o.user_id='00000000-0000-4000-8000-000000000001'::uuid;
  -- No business records remain in JSON; this table now holds revision metadata.
  update public.atlas_workspaces set payload='{"clientes":[],"categorias":[],"itens":[],"orcamentos":[],"itensOrcamento":[]}' where user_id='00000000-0000-4000-8000-000000000001'::uuid;
  select loaded.payload into result_payload from public.atlas_load_workspace() loaded;
  return jsonb_build_object('revision',saved->'revision','payload',result_payload);
end;
$$;

revoke all on function public.atlas_save_workspace(bigint,jsonb) from public,anon;
grant execute on function public.atlas_save_workspace(bigint,jsonb) to authenticated;
commit;
