-- Apply after migrations 001 and 002. Preserve existing codes and references.
begin;
lock table public.atlas_workspaces in exclusive mode;
lock table public.cliente in access exclusive mode;
alter table public.cliente alter column codigo add generated always as identity;
select setval(pg_get_serial_sequence('public.cliente', 'codigo'),
  coalesce((select max(codigo) from public.cliente), 1),
  exists(select 1 from public.cliente));
do $migration$
begin
  execute format('revoke all on sequence %s from public, anon, authenticated',
    pg_get_serial_sequence('public.cliente', 'codigo'));
end;
$migration$;
update public.atlas_workspaces set revision = revision + 1;

-- The response now includes the client codes assigned by PostgreSQL.
drop function public.atlas_save_workspace(bigint,jsonb);
create function public.atlas_save_workspace(expected_revision bigint, new_payload jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare next_revision bigint;
begin
  if auth.uid() is null or coalesce((auth.jwt()->>'is_anonymous')::boolean, false) then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if jsonb_typeof(new_payload->'clientes') is distinct from 'array' then
    raise exception 'Invalid client collection' using errcode = '22023';
  end if;
  if exists (
    select 1 from jsonb_array_elements(new_payload->'clientes') as client
    where jsonb_typeof(client) <> 'array'
  ) then raise exception 'Invalid client row' using errcode = '22023'; end if;
  if exists (
    select 1 from jsonb_array_elements(new_payload->'clientes') as client
    where jsonb_array_length(client) <> 4
      or jsonb_typeof(client->0) not in ('number', 'null')
  ) then raise exception 'Invalid client row' using errcode = '22023'; end if;

  if expected_revision = 0 then
    insert into public.atlas_workspaces(user_id, payload)
      values (auth.uid(), jsonb_set(new_payload, '{clientes}', '[]'::jsonb))
      on conflict do nothing returning revision into next_revision;
  else
    update public.atlas_workspaces
      set payload = jsonb_set(new_payload, '{clientes}', '[]'::jsonb),
          revision = revision + 1, updated_at = now()
      where user_id = auth.uid() and revision = expected_revision
      returning revision into next_revision;
  end if;
  if next_revision is null then return null; end if;

  -- Supplied codes may only identify this user's existing clients.
  if exists (
    select 1 from jsonb_array_elements(new_payload->'clientes') as client
    where client->>0 is not null and not exists (
      select 1 from public.cliente as existing
      where existing.user_id = auth.uid() and existing.codigo = (client->>0)::bigint
    )
  ) then raise exception 'New client codes must be generated by the database' using errcode = '22023'; end if;
  if exists (
    select client->>0 from jsonb_array_elements(new_payload->'clientes') as client
    where client->>0 is not null group by client->>0 having count(*) > 1
  ) then raise exception 'Duplicate client code' using errcode = '22023'; end if;

  delete from public.cliente as existing
    where existing.user_id = auth.uid() and not exists (
      select 1 from jsonb_array_elements(new_payload->'clientes') as client
      where (client->>0)::bigint = existing.codigo
    );
  update public.cliente as existing
    set tipo = client->>1, documento = client->>2, nome = client->>3
    from jsonb_array_elements(new_payload->'clientes') as client
    where existing.user_id = auth.uid() and existing.codigo = (client->>0)::bigint;
  insert into public.cliente(user_id, tipo, documento, nome)
    select auth.uid(), client->>1, client->>2, client->>3
    from jsonb_array_elements(new_payload->'clientes') as client
    where client->>0 is null;

  return jsonb_build_object('revision', next_revision, 'clientes', coalesce((
    select jsonb_agg(jsonb_build_array(codigo, tipo, documento, nome) order by codigo)
    from public.cliente where user_id = auth.uid()
  ), '[]'::jsonb));
end;
$$;
revoke all on function public.atlas_save_workspace(bigint,jsonb) from public, anon;
grant execute on function public.atlas_save_workspace(bigint,jsonb) to authenticated;
commit;
